namePrefix: metricbeat-
commonLabels:
  k8s-app: metricbeat
resources:
  - ../../base/beat
  - modules-configmap.yaml
images:
  - name: docker.elastic.co/beats/beat
    newName: docker.elastic.co/beats/metricbeat
    newTag: "8.5.0"
patchesStrategicMerge:
  - configmap.yaml
  - cluster-role.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "-c"
          - "/etc/metricbeat.yml"
          - "-e"
          - "-system.hostfs=/hostfs"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: metricbeat
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
        value: /etc/metricbeat.yml
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/subPath
        value: metricbeat.yml
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/1/mountPath
        value: /usr/share/metricbeat/data
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: proc
          mountPath: /hostfs/proc
          readOnly: true
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /var/lib/metricbeat-data
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: proc
          hostPath:
            path: /proc
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: cgroup
          hostPath:
            path: /sys/fs/cgroup
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: modules
          configMap:
            defaultMode: 0640
            name: metricbeat-modules-configmap
    target:
      kind: DaemonSet
      name: daemonset
