metricbeat.config.modules:
  # Mounted `metricbeat-daemonset-modules` configmap:
  path: ${path.config}/modules.d/*.yml
  # Reload module configs as they change:
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: kubernetes
      scope: cluster
      node: ${NODE_NAME}
      # In large Kubernetes clusters consider setting unique to false
      # to avoid using the leader election strategy and
      # instead run a dedicated Metricbeat instance using a Deployment in addition to the DaemonSet
      unique: true
      templates:
        - config:
            - module: kubernetes
              hosts: ["${KUBE_STATE_METRICS}:8080"]
              period: 10s
              add_metadata: true
              metricsets:
                - state_node
                - state_deployment
                - state_daemonset
                - state_replicaset
                - state_pod
                - state_container
                - state_job
                - state_cronjob
                - state_resourcequota
                - state_statefulset
                - state_service
              # If `https` is used to access `kube-state-metrics`, uncomment following settings:
              # bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              # ssl.certificate_authorities:
              #   - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            - module: kubernetes
              metricsets:
                - apiserver
              hosts: ["https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"]
              # bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              bearer_token_file: ${SERVICE_ACCOUNT_TOKEN_FILE}
              ssl.certificate_authorities:
                # - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                - ${CA_CRT_FILE}
              period: 30s
            # Uncomment this to get k8s events:
            #- module: kubernetes
            #  metricsets:
            #    - event
    # To enable hints based autodiscover uncomment this:
    #- type: kubernetes
    #  node: ${NODE_NAME}
    #  hints.enabled: true

processors:
  - add_cloud_metadata:

cloud.id: ${ELASTIC_CLOUD_ID}
cloud.auth: ${ELASTIC_CLOUD_AUTH}

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
  protocol: https
  ssl.verification_mode: "none"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  allow_older_versions: true
