apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
spec:
  selector:
    matchLabels:
      k8s-app: beat
  template:
    metadata:
      labels:
        k8s-app: beat
    spec:
      serviceAccountName: service-account
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: beat
        image: docker.elastic.co/beats/beat:8.5
        args: [
          "-c",
          "/etc/beat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTIC_CLOUD_ID
          value: ""
        - name: ELASTIC_CLOUD_AUTH
          value: ""
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/beat.yml
          readOnly: true
          subPath: beat.yml
        - name: data
          mountPath: /usr/share/beat/data
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: configmap
      - name: data
        hostPath:
          path: /var/lib/beat-data
          type: DirectoryOrCreate
