apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeadm-config-role
rules:
  - apiGroups:
      - ""
    resourceNames:
      - kubeadm-config
    resources:
      - configmaps
    verbs:
      - get
