# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - kubectl apply -f service-account.yml
      - kubectl -n kube-system create token metricbeat > tokens/service-account-token.txt
      - kubectl port-forward -n kube-system {{.POD_NAME}} 10249:10249
    vars:
      POD_NAME:
        sh: kubectl get pods -l k8s-app=kube-proxy -n kube-system -o jsonpath='{.items[0].metadata.name}'
