# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  beat:
    cmds:
      - kustomize build overlays/{{.BEAT}} --reorder=none > {{.OUTPUT_FILE}}
    vars:
      BEAT: '{{default "filebeat" .BEAT}}'

      # OUTPUT_FILE: "{{.BEAT}}-kubernetes.tmp.yaml"
      OUTPUT_FILE: "{{.BEAT}}-kubernetes.yaml"

  filebeat:
    cmds:
      - task: beat
        vars:
          BEAT: filebeat

  metricbeat:
    cmds:
      - task: beat
        vars:
          BEAT: metricbeat
